this fixes error on gui start 'dict' object has no attribute 'write' in Kali linux and probably debian and ubuntu
Basically a dict object was being past to a function that expected something with a .write attribute
the file object has tat so I switch around the file obj and "{}" obj because it made sense.  After that it started no problem


Traceback (most recent call last):
  File "/opt/git/w3af/w3af_gui", line 110, in <module>
    _main()
  File "/opt/git/w3af/w3af_gui", line 106, in _main
    sys.exit(main())
  File "/opt/git/w3af/w3af_gui", line 101, in main
    gui_main(profile, doupdate)
  File "/opt/git/w3af/w3af/core/ui/gui/main.py", line 936, in main
    MainApp(profile, do_upd)
  File "/opt/git/w3af/w3af/core/ui/gui/main.py", line 413, in __init__
    self.pcbody = pluginconfig.PluginConfigBody(self, self.w3af)
  File "/opt/git/w3af/w3af/core/ui/gui/pluginconfig.py", line 601, in __init__
    alertmodif=mainwin.profile_changed)
  File "/opt/git/w3af/w3af/core/ui/gui/entries.py", line 468, in __init__
    alertmodif=alertmodif)
  File "/opt/git/w3af/w3af/core/ui/gui/entries.py", line 405, in __init__
    self.hist = history.HistorySuggestion(historyfile)
  File "/opt/git/w3af/w3af/core/ui/gui/history.py", line 62, in __init__
    msgpack.dump(file(filename, 'wb'), {})
  File "/usr/local/lib/python2.7/dist-packages/msgpack/__init__.py", line 38, in pack
    stream.write(packer.pack(o))
AttributeError: 'dict' object has no attribute 'write'