passed in variables to msgpack.dump are in the wrong order just like they were on line 62 in teh previous checkin
so the call to msgpack.dump on line 69 had the passed-in variables in the wrong order just like they were on line 62 in the previous commit, so on subsequent loads the app failed to start because now there was history and the call got placed to a different line in the code.
here is the error (very similar to the last one)
Traceback (most recent call last):
  File "./w3af_gui", line 110, in <module>
    _main()
  File "./w3af_gui", line 106, in _main
    sys.exit(main())
  File "./w3af_gui", line 101, in main
    gui_main(profile, doupdate)
  File "/opt/git/w3af/w3af/core/ui/gui/main.py", line 936, in main
    MainApp(profile, do_upd)
  File "/opt/git/w3af/w3af/core/ui/gui/main.py", line 413, in __init__
    self.pcbody = pluginconfig.PluginConfigBody(self, self.w3af)
  File "/opt/git/w3af/w3af/core/ui/gui/pluginconfig.py", line 601, in __init__
    alertmodif=mainwin.profile_changed)
  File "/opt/git/w3af/w3af/core/ui/gui/entries.py", line 468, in __init__
    alertmodif=alertmodif)
  File "/opt/git/w3af/w3af/core/ui/gui/entries.py", line 405, in __init__
    self.hist = history.HistorySuggestion(historyfile)
  File "/opt/git/w3af/w3af/core/ui/gui/history.py", line 69, in __init__
    msgpack.dump(file(filename, 'wb'), self.history)
  File "/usr/local/lib/python2.7/dist-packages/msgpack/__init__.py", line 38, in pack
    stream.write(packer.pack(o))
AttributeError: 'dict' object has no attribute 'write'